recipe: default.v1
language: en
version: "3.1"
 
pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 60
    entity_recognition: true
    intent_classification: true
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 60
  - name: FallbackClassifier
    threshold: 0.4
    ambiguity_threshold: 0.1
 
policies:
  - name: MemoizationPolicy
  - name: RulePolicy
    core_fallback_action_name: "action_out_of_scope"
    core_fallback_threshold: 0.05  
    enable_fallback_prediction: true
  - name: UnexpecTEDIntentPolicy
    max_history: 5
    epochs: 20
  - name: TEDPolicy
    max_history: 5
    epochs: 20
    constrain_similarities: true
 
assistant_id: 20250716-123720-mild-coverage
